### ISSUE TITLE
Display Issues with Persian/Arabic Text

### ISSUE THREAD

**Issue by omidmnz** [mickeynp/ligature.el#11]
Characters tend to be glued together in Persian/Arabic texts, and Emacs can display them without problems. Enabling `ligature-mode` breaks that, as [these screenshots](https://imgur.com/a/ize7Y0N) demonstrate. I don't know what other information would be helpful, but I'm ready to provide more information in case more is needed.

Edit: I'm using Iosevka as the main font, while switching to another (Samim) font to Persian text.

**Comment by omidmnz** [comment]
With the fix in the submitted pull request, both Persian text and Ligatures are rendered correctly. (As seen [here](https://imgur.com/a/ntHydMK).)

The problem was that ligature.el replaced the default char-table with another one. The pull request adds the existing char-table as a parent to ligature.el's, so Emacs can render characters properly when they don't appear in ligature.el's char-table.

**Comment by simurgh9** [comment]
@omidmnz could you try [cascadia-code](https://github.com/microsoft/cascadia-code) for a second without switching to Samim since Cascadia supports Arabi and see if you get this issue https://github.com/microsoft/cascadia-code/issues/628

Essentially, Alif in constructs like `لا با پا نا` disappears and words like `لیکن` are not adjoined correctly.

**Comment by omidmnz** [comment]
> @omidmnz could you try [cascadia-code](https://github.com/microsoft/cascadia-code) for a second without switching to Samim since Cascadia supports Arabi and see if you get this issue [microsoft/cascadia-code#628](https://github.com/microsoft/cascadia-code/issues/628)
> 
> Essentially, Alif in constructs like `لا با پا نا` disappears and words like `لیکن` are not adjoined correctly.

Yes. I do. `لیکن` looks correct for me, but all the Alef letters disappear, just like the picture in the referenced issue.

**Comment by simurgh9** [comment]
Could you drop a little comment on that issue so the kind people at Microsoft could maybe take a notice? The issue is now a couple months old.
