### ISSUE TITLE
Ligatures of 3 three or more characters are not rendered correctly

### ISSUE THREAD

**Issue by thomasheartman** [mickeynp/ligature.el#18]
Hey,

Thanks for the great package! I've been missing ligature support in Emacs for a long time now, so it's great to see this package pop up. However, I ran into a rendering problem when setting it up.

# Issue

I've got an issue where it seems that ligatures that consist of three or more characters aren't rendered correctly most of the time.

Below is an image of what the default config in the readme looks like when rendered with Cascadia Code using ligatures.

It seems to Render all 2-character glyphs correctly, but most of the glyphs that consist of more characters are rendered incorrectly. By 'incorrectly' I mean different to what I'd expect based on the image in the readme. Particularly noticeable examples are `<==>`, `<==`, and `<=>`, `!==` and `===`, and `->>` and `<=<`. 

![image](https://user-images.githubusercontent.com/17786332/102886740-f2b83700-4455-11eb-90d8-32c83a1d8e23.png)

## Cause and solution?

It strikes me that most, if not all, of these glyphs consist of smaller  clusters that are also valid glyphs on their own. So it seems that this may indeed be a case of Emacs picking the first/smallest cluster that it finds and creating an appropriate cluster. And indeed, removing the `"=="` entry from the list fixes the issues relating to character clusters that contain `==`. 

In theory I could use the more complex way of creating ligatures that is described in the readme, but it doesn't seem to me like it should be needed (based on the other examples).

# System info:

OS: macOS Catalina, version 10.15.7 
Emacs version: GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin19.2.0, NS appkit-1894.20 Version 10.15.2 (Build 19C57)) of 2020-01-14

**Comment by thomasheartman** [comment]
A little update on this. I just tried it out on my NixOS system using 'GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.21, cairo version 1.16.0)'. On this system, everything works as expected and all the glyphs appear to render correctly. So it seems that there's probably something macOS-specific going on here.

**Comment by mickeynp** [comment]
Thomas, it may also be the order in which the ligation is applied as Emacs uses regexp to ligate the characters. I did encounter an issue where Emacs would greedily pick the first 'match' if the order of the regexp was not set up correctly and I did implement a little checking for that also, but it's possible macs behave differently also.

**Comment by thomasheartman** [comment]
Aye. It could also be that there is something in Emacs 28 that changes how it works. I don't know which is more or less likely, though. In general, though, I'd expect the same bit of lisp code to do the same thing, so maybe there _is_ a change in Emacs 28 that impacts this. Anyway, that's just speculation on my part.

**Comment by thomasheartman** [comment]
Update: I just tried using the native-comp branch of Emacs 28 (GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.7 (Build 19H15) to be exact), and the ligatures display correctly there, so it may be something that's been fixed since I last updated. It could also be that the version of Emacs I usually use is missing some other patch.

In short, I'm not sure this is an issue anymore and don't think it warrants spending a lot of time fixing (unless anyone else seems to have similar issues). I'll leave it up to you, of course, but feel free to close this issue if you think that's the right thing to do. Thanks for your input!

**Comment by mickeynp** [comment]
@thomasheartman, 

Can you check if this example snippet yields better results for you:
```elisp
(ligature-set-ligatures 'markdown-mode `(("=" ,(rx (+ "=") (? (| ">" "<"))))
                                         ("-" ,(rx (+ "-")))))
```

This should yield variable length ligations and arrows in markdown-mode, but you can of course customise this to suit your needs.

**Comment by thomasheartman** [comment]
Hey, @mickeynp! Thanks for following up on this. Unfortunately I don't have have the system where I can try this out anymore, so there's not much I can do here.
