### ISSUE TITLE
fix for your example

### ISSUE THREAD

**Issue by jstaursky** [mickeynp/ligature.el#19]
Hey your example "`(use-package ligature ..`" almost works but I had to remove  `"\\"` (using libcairo 1.15 btw)
cheers

**Comment by mickeynp** [comment]
Thanks @jstaursky.

Did it crash or not render right?

**Comment by jstaursky** [comment]
No ligatures worked until I removed those characters. Then it worked. Might be due to a difference in cascadia versions.
