### ISSUE TITLE
disable ligature when repetition detected

### ISSUE THREAD

**Issue by andreyorst** [mickeynp/ligature.el#20]
Currently when I use ligature for `===` in Emacs repeatedly I like this:

```
=
==
===
====
=====
======
```

Emacs displays the following text:

![image](https://user-images.githubusercontent.com/19470159/104747392-83d2b300-5761-11eb-8d2d-8dfd7af45028.png)

Atom, for example, displays this:

![image](https://user-images.githubusercontent.com/19470159/104747506-ab298000-5761-11eb-9f44-bd0870eb6c29.png)

Repeated characters often used as code separators, and in block comments, which doesn't look right:

```
***
/*********************************************
 * important note ahead, pay close attention *
 *********************************************/
```
In Emacs:

![image](https://user-images.githubusercontent.com/19470159/104747844-0ce9ea00-5762-11eb-95d4-ee8b2d82763a.png)

And in Intellij IDEA this looks like this:

![image](https://user-images.githubusercontent.com/19470159/104747778-f6dc2980-5761-11eb-8676-35bb0cc64c4a.png)

I think ligatures are supposed to be used where they belong, not everywhere, so simply searching if pattern matches some ligature is not the right approach. Testing if ligature is not part of the word is not an option either, as some languages have operators like this:

```clojure
some->
some->>
```
This is a correct result and it should be kept:

![image](https://user-images.githubusercontent.com/19470159/104748075-5803fd00-5762-11eb-8713-63707c0296fb.png)

I've also noticed that Emacs honors beginning of the ligature, while other editors honor ending:

```
<->>
```

Emacs:  
![image](https://user-images.githubusercontent.com/19470159/104748357-b16c2c00-5762-11eb-8563-8411960c26ee.png)
Atom:
![image](https://user-images.githubusercontent.com/19470159/104748305-9ef1f280-5762-11eb-9de7-60a9ac543db8.png)
Intellij: ![image](https://user-images.githubusercontent.com/19470159/104748279-94375d80-5762-11eb-9643-bafdcdb17f96.png)

This may be another property that helps with detecting repetitions.

**Comment by andreyorst** [comment]
one possible solution would to attach the character group that ensures that regex is never followed by any of the characters that can be the beginning of a ligature. E.g. if ligatures can begin with `-`, `=`, and `~`, each ligature regexp must contain `\\(?:[^-=~]+\\|$\\)` at the end. However this doesn't work quite well:

![image](https://user-images.githubusercontent.com/19470159/104834463-80017680-58b0-11eb-8cf5-ad9cebdccc94.png)

Adding the same kind of regex (`\\(?:^\\|[^-=~]+\\)` *before* the pattern will break everything that is not at the beginning of the line. It seems that char-composition-table does only the forward search, so this is not possible to check what's behind

**Comment by mickeynp** [comment]
@andreyorst 

I believe the version in the master branch can at least fix some of these issues:

```elisp
  (ligature-set-ligatures t '(("=" (rx "=" (+ "=")))
                              ("*" (rx "*" (+ "*")))))

```
You can use `rx` to compile your own regexps; of course it does not support reversing the order as the underlying composition engine in theory does. But it should at least ensure that most things will render right, including variable-length ligations like `***` vs `****`.

Can you check that this works for you?

**Comment by andreyorst** [comment]
I'm not sure if I understand why this should work. If I set up regex that is of fixed amount of characters, like you mention in the second to last sentence, it will indeed show ligature only for `***` and not for `****`, however the problem will occur once `******` is met, as the engine seems not to take into account what goes after the regex match.

I've actually solved this problem in my current configuration, but only partially because it introduces another problem. The most annoying one is that if I set the regex for `=` as `[^=]\\(=\|==\|===\)[^=]` and set lookbehind of composing engine to 1 char it works but will actually compose following character and produce weird results, like composing a newline into ligature removes newline visually from buffer. So this isn't as simple as just fixing the amount I guess.

**Comment by mickeynp** [comment]
I'm not sure what issue you are reporting. The example I gave will perfectly well represent the ligatures as Atom and IntelliJ does.

This complete example should amply demonstrate what I mean and accurately reproduce what you want. Of course the existing _Cascadia Code_ example does not have variable-length ligatures so the example snippet does not include any. You could make the case that ligature.el should automatically composit _ahead_ of the end of a simple string ligature like `===` by representing it internally as `=\{3,\}` perhaps. However, it does not do that by default and I don't think it should either as I can imagine that might cause weird issues with other rules as the regexp is essentially far too greedy.

You will have to amend the ligatures to map to what you want them to be on your end.

Example:
```elisp
(with-current-buffer (get-buffer-create "ligature-test")
  (setq ligature-composition-table nil)
  (ligature-set-ligatures t '(("=" (rx (+ "=")))
                              ("*" (rx (+ "*")))))
  (ligature-mode -1)
  (ligature-mode t)
  (dolist (s '("=" "==" "===" "====" "=====" "======"
               "*" "**" "***" "****" "*****" "******"
               "/*******/"
               "/***/"))
    (insert s "\n"))
  (switch-to-buffer "ligature-test"))
```

**Comment by andreyorst** [comment]
Ah, hm. Sorry, perhaps I've misunderstood your initial comment. Yes, this works. Can this package do so by default when provided a list of ligatures (as described in readme section)?

**Comment by andreyorst** [comment]
sorry, decided to reopen for the sake of this: 

> Can this package do so by default when provided a list of ligatures (as described in readme section)?

**Comment by andreyorst** [comment]
damn, sorry, I've re-re-read your message and spotted

> However, it does not do that by default and I don't think it should either as I can imagine that might cause weird issues with other rules as the regexp is essentially far too greedy.

Sorry for bothering! I'll override certain ligatures as you suggest
