### ISSUE TITLE
Suboptimal regular expressions in composition rules?

### ISSUE THREAD

**Issue by Eli-Zaretskii** [mickeynp/ligature.el#22]
The way composition rules work, whenever Emacs encounters a character whose cell in `composition-function-table` is non-nil, it loops over all the rules that could potentially match, looking for the rule it should use.  Ligatures for programming modes use many sequences that begin with the same character (e.g., look how many sequences in the ligatures set for `prog-mode` begin with `<` or with `=`).  Instead of having a large number of strings to match that begin with the same character, wouldn't it be better to make a single regexp from them using `regex-opt`, so that each character's rule used only one regexp?  This could potentially make redisplay faster.

**Comment by mickeynp** [comment]
Hi Eli,

Thanks for showing an interest - I really appreciate it.

The underlying code already does that (and it used to use `regexp-opt` but I later merged it with `rx`'s own grouping code to allow users to inject custom `rx` forms and seamlessly merge them.) So the end result should be that all ligations that begin with a certain char are merged properly behind-the-scenes. I figured it was much easier for a user to manually type out most of the ligatures they wanted (and fall back to custom `rx` forms for complex ligatures) and let the underlying code figure out the most efficient internal representation that gets passed to `composition-function-table`.
