### ISSUE TITLE
;; ligature misapplied for more than two semicolons in a row

### ISSUE THREAD

**Issue by luismbo** [mickeynp/ligature.el#27]
Let's say `<;;>` represents the ligature for two semicolons. ligature.el will then convert `;; comment` to `<;;> comment` and that is fine. However it'll convert `;;; comment` and `;;;; comment` to `<;;>; comment` and `<;;><;;> comment` which doesn't look quite right.

FWIW, other applications apply the ligature for `;;` but not `;;;` or `;;;;`.

I tried to use `"[^;];;[^;]"` in `ligature-set-ligatures`, but that for some reason fixed `;;;` but not `;;;;`.

In any case, it's nice that I can disable individual ligatures and it's what I currently do for `;;` and a couple of others that don't look so good for Lisp code and that's fine. Thanks for writing this mode!

**Comment by mickeynp** [comment]
I think this is going to be one of those things that's controversial; some may prefer one or the other. Having said that, you can create a custom ligature for just those modes like so:

```elisp
(ligature-set-ligatures '(emacs-lisp-mode lisp-interaction-mode) '((";" (rx (* ";")))))
```
Which should do the trick of ligating just `;;` and nothing else.

**Comment by luismbo** [comment]
Thanks!
