### ISSUE TITLE
publish on melpa

### ISSUE THREAD

**Issue by wbolster** [mickeynp/ligature.el#28]
🙏

**Comment by mickeynp** [comment]
I'd love to, but as it's in theory broken in Emacs 27.1 and the upcoming Emacs 27.2 due to a bug in Emacs's core, I feel I should wait until it's actually fixed or risk a flood of complaints.

**Comment by rski** [comment]
would setting the package-requires to emacs-28 and publishing it on melpa prevent it from being installed on older emacsen with the bug? If anyone with emacs-27 really wants it, they can manually install it, same way as everyone has to do it now anyway.

**Comment by mickeynp** [comment]
It'll appear on melpa when Emacs 28 is out.

**Comment by chvp** [comment]
[28.1 has been released.](https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=de7901abbc21114721057c907cc52455e228f826)

**Comment by 4lph4-Ph4un** [comment]
> It'll appear on melpa when Emacs 28 is out.

Anything new on the melpa-front? As the previous commenter has mentioned, 28.1 is out in the wild and pretty stable!
