### ISSUE TITLE
Falls into an infinite loop

### ISSUE THREAD

**Issue by djarb** [mickeynp/ligature.el#3]
After a few minutes of editing source code, while ligature.el is loaded and active, my emacs gets caught up in an infinite loop or endless recursion, to the point where I have to use job control to terminate the process. Due to the nature of the symptom, I haven't been able to isolate the cause for you.

I was using it with Fira Code and the following configuration:
 (use-package ligature
   :config
   ;; Enable the "www" ligature in every possible major mode
   (ligature-set-ligatures 't '("www"))
   (ligature-set-ligatures 'prog-mode '("||" "&&" "!!" "lambda" "" "<=" ">=" "!=" "==" "===" "!=="
                                        "=>" "->" "<-" "and" "or" "not" "::" ":=" "++" "--" "..=" "<->" "<~>"
                                        "/=" "*=" "+=" "-=" "__" "<=>" "/*" "*/" "//" "///" "\n" "\\" "**"
                                        "</" "#" "##" "###" "####" "#####" "######" "?." "??" ".." "..." ":::"
                                        "0x0" "0x1" "0x2" "0x3" "0x4" "0x5" "0x6" "0x7" "0x8" "0x9" "0xA" "0xa"
                                        "0xB" "0xb" "0xC" "0xc" "0xD" "0xd" "0xE" "0xe" "0xF" "0xf" "0b0" "0b1"
                                        "0o0" "0o1" "0o2" "0o3" "0o4" "0o5" "0o6" "0o7"))
   (global-ligature-mode t))

**Comment by mickeynp** [comment]
I think I have a vague idea. I assume you're following the installation criteria, though, right?

It's possible some of the ligatures are broken -- or the interaction between harfbuzz, emacs and the font cause issues. 

My recommendation is to bisect the set of ligatures by commenting out half of them, see if it makes a difference; rinse, repeat until you find out which one(s) are causing issues.

There are other people [https://github.com/tonsky/FiraCode/issues/517](with similar issues) in Emacs. I suspect this is likely the problem.

**Comment by djarb** [comment]
Ah, that's possible. Some of the ligatures I specified aren't even in Fira Code, I just added them optimistically in case they ever turned up. I'll test and see if eliminating them fixes this.

**Comment by djarb** [comment]
Okay, narrowing the ligature list to only contain ligatures currently supported by the font appears to have fixed the problem. This might make a good FAQ entry when you publish. Thanks!

**Comment by djarb** [comment]
One final note: you may want to recognize and warn about ligature list entries consisting of a single character, which is another thing I carelessly did in my problematic ligature list.

**Comment by mickeynp** [comment]
Thanks for the update. I'm glad that resolved it. I'm curious why your system misbehaves when incorrect ligatures are added: I did not experience that with Cascadia Code. I will have to investigate and see if it's related to the font or the system configuration.

Thanks again.
