### ISSUE TITLE
How to deal with arbitrary long ligatures?

### ISSUE THREAD

**Issue by kenkangxgwe** [mickeynp/ligature.el#4]
Such as `----------------------------->`? Is there a syntax to detect this kind of patterns? Thanks

**Comment by mickeynp** [comment]
Yes, you will need to amend the table directly, like so:

```elisp
(add-to-list 'ligature-composition-table `(rst-mode ("-" . ,(rx (+ "-") ">"))))
```
(untested)

There's an example in the documentation that closely resembles this one. I recommend you read that part carefully. Particularly the part about overwriting existing ligature mappings. I will see if I can add a feature to help do this for you automatically in the meantime.

**Comment by kenkangxgwe** [comment]
Thanks Mickey. Will give a try
