### ISSUE TITLE
Ligatures take up only one character's space, regardless of original number of characters

### ISSUE THREAD

**Issue by kchousos** [mickeynp/ligature.el#42]
Ligatures disabled:
![image](https://user-images.githubusercontent.com/79325777/194722879-06431aea-a3cc-4f6e-9662-bebc34343edd.png)
Ligatures enabled:
![image](https://user-images.githubusercontent.com/79325777/194722894-3f32965e-181a-4fd9-a125-4e1652b02e14.png)

My relevant configuration is the following:
```emacs-lisp
(use-package ligature
  :straight (:host github :repo "mickeynp/ligature.el")
  ;; Enable traditional ligature support in eww-mode, if the
  ;; `variable-pitch' face supports it
  :config
  ;; Enable all programming ligatures in programming modes
  (ligature-set-ligatures 'prog-mode '(":::" "::=" "&&" "||" "::" ":=" "==" "!=" ">=" ">>" "<="
                                       "<<" "??" ";;" "->" "<-" "-->" "<--"
                                       ))
  ;; Enables ligature checks globally in all buffers. You can also do it
  ;; per mode with `ligature-mode'.
  (global-ligature-mode t))
```

The same thing happens with ligatures of two characters like `!=` or `<=`.

Emacs version: `GNU Emacs 29.0.50 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6) of 2022-09-19`

I really like this package but this makes it unusable. Is there any solution available? Thank you in advance.

**Comment by mickeynp** [comment]
Does it happen with other ligatures?

**Comment by kchousos** [comment]
It happened with all ligatures, but after some days it just fixed itself. Can't remember if I did an update or not. Either way, it's not a problem anymore. Thank you very much for your time and hard work.
