### ISSUE TITLE
JuliaMono support

### ISSUE THREAD

**Issue by MasonProtter** [mickeynp/ligature.el#45]
Hey, great package. Would you be interested in supporting the font [JuliaMono](https://juliamono.netlify.app/)? I find it's my favourite for working with a lot of unicode and has some nice ligatures.

**Comment by mickeynp** [comment]
That'd be most welcome. Can you add it to the wiki?

**Comment by MasonProtter** [comment]
Hi @mickeynp, I think only people with permissions are allowed to edit the wiki which I don't have, and strangely Github doesn't support Wiki PRs :disappointed: 

However, here are the relevant ligatures if you want to put it in:
```
(use-package ligature
  :load-path "path-to-ligature-repo"
  :config

  ;; JuliaMono (https://juliamono.netlify.app/) supports the following small set of ligatures 
  (let ((ligs '("->" "=>" "|>" "<|" "::" "<--" "-->" "<-->")))
	  (ligature-set-ligatures 'prog-mode ligs)
	  (ligature-set-ligatures 'org-mode ligs))

  ;; Enables ligature checks globally in all buffers. You can also do it
  ;; per mode with `ligature-mode'.
  (global-ligature-mode t))
```

**Comment by mickeynp** [comment]
Thanks! I'll update the wiki.
