### ISSUE TITLE
Error (use-package): Cannot load ligature

### ISSUE THREAD

**Issue by danieljamesross** [mickeynp/ligature.el#9]
Emacs Version 27.1 (9.0)
Mac OS 10.13.6

Hello,

I cloned the repo and followed the steps in the README using the Cascadia Code demo but I get the following error:

`Error (use-package): Cannot load ligature`

If I try and load `ligature.el` by hand using `M-x package-install-file` I get another error:

`Debugger entered--Lisp error: (error "Package lacks a \"Version\" or \"Package-Version\" header")
  signal(error ("Package lacks a \"Version\" or \"Package-Version\" header"))
  error("Package lacks a \"Version\" or \"Package-Version\" header")
  package-buffer-info()
  package-install-from-buffer()
  package-install-file("~/.emacs.d/ligature.el/ligature.el")
  funcall-interactively(package-install-file "~/.emacs.d/ligature.el/ligature.el")
  call-interactively(package-install-file record nil)
  command-execute(package-install-file record)
  execute-extended-command(nil "package-install-file" "package-install-fi")
  funcall-interactively(execute-extended-command nil "package-install-file" "package-install-fi")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
`

Any help greatly appreciated.

Cheers,
Dan

**Comment by To1ne** [comment]
It's not on [MELPA](https://melpa.org/#/?q=ligature), nor I'm seeing [a PR for it](https://github.com/melpa/melpa/pulls?q=is%3Apr+is%3Aopen+ligature) yet. I guess someone just needs to add it.

**Comment by mickeynp** [comment]
It's not quite ready for prime time yet; but it will appear on MELPA once the package has stabilised.

**Comment by danieljamesross** [comment]
Thanks both. Can I not install without Melpa? Or should I wait?

**Comment by mickeynp** [comment]
If you follow the sample guide you will see that it needs a `load-path` that points to the github repo.

**Comment by danieljamesross** [comment]
No I did try that first:

"I cloned the repo and followed the steps in the README using the Cascadia Code demo but I get the following error:

Error (use-package): Cannot load ligature"

**Comment by To1ne** [comment]
@danieljamesross You must have made a typo in the path somewhere. Please double check the path you're passing to `:load-path` in the `use-package` macro.

Something like:

```sh
cd ~/.emacs.d/elisp
git clone git@github.com:mickeynp/ligature.el.git ligature
```

(I'm passing `ligature` as extra argument to name the directory without `.el`)

```elisp
(use-package ligature
  :load-path (expand-file-name "elisp/ligature/" user-emacs-directory)
  :config
  ;; Enable the "www" ligature in every possible major mode
  (ligature-set-ligatures 't '("www"))
  (global-ligature-mode t))
```

**Comment by danieljamesross** [comment]
Gah, you were right, spelling mistake. Apologies and thanks for your time!
